# Generated by Django 5.1.7 on 2025-03-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoRastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=255)),
                ('path_minio', models.CharField(max_length=500, unique=True)),
                ('bucket', models.CharField(max_length=100)),
                ('tipo_arquivo', models.CharField(max_length=50)),
                ('tamanho', models.BigIntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('md5_hash', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Arquivo Rastreado',
                'verbose_name_plural': 'Arquivos Rastreados',
                'db_table': 'arquivos_rastreamento',
            },
        ),
    ]
