# Generated by Django 5.1.7 on 2025-06-02 00:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('nivel', models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor')], max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_loja', models.CharField(blank=True, help_text='Código de 3 dígitos da loja (NUMLOJ no SysFat)', max_length=3, null=True)),
                ('codigo_vendedor', models.CharField(blank=True, help_text='Código de 3 dígitos do vendedor (CODVEN no SysFat)', max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('codigo_master', models.CharField(blank=True, help_text='Se preenchido, indica que este é um sub-cliente', max_length=20, null=True, verbose_name='Código Master')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('rascunho', 'Rascunho')], default='ativo', max_length=10, verbose_name='Status')),
                ('tipo_logradouro', models.CharField(blank=True, help_text='Ex: Rua, Avenida, Alameda, etc.', max_length=20, null=True, verbose_name='Tipo de Logradouro')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('data_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Data da Última Compra')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('codigo_loja', models.CharField(blank=True, help_text='Código de 3 dígitos da loja (NUMLOJ no SysFat)', max_length=3, null=True, verbose_name='Código da Loja')),
                ('codigo_vendedor', models.CharField(blank=True, help_text='Código de 3 dígitos do vendedor (CODVEN no SysFat)', max_length=3, null=True, verbose_name='Código do Vendedor')),
                ('nome_vendedor', models.CharField(blank=True, help_text='Nome do vendedor (VEND no SysFat)', max_length=100, null=True, verbose_name='Nome do Vendedor')),
                ('uf', models.CharField(blank=True, help_text='Unidade Federativa (UF no SysFat)', max_length=2, null=True, verbose_name='UF')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('tipo_documento', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], default='cpf', max_length=10, null=True, verbose_name='Tipo de Documento')),
                ('nome_razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome/Razão Social')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Municipal')),
                ('situacao_cadastral', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação Cadastral')),
                ('data_situacao_cadastral', models.DateField(blank=True, null=True, verbose_name='Data da Situação Cadastral')),
                ('motivo_situacao_cadastral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo da Situação Cadastral')),
                ('data_ultima_verificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Verificação')),
                ('natureza_juridica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza Jurídica')),
                ('codigo_natureza_juridica', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Natureza Jurídica')),
                ('porte_empresa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Porte da Empresa')),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE Principal')),
                ('cnae_descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do CNAE')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('data_inicio_atividade', models.DateField(blank=True, null=True, verbose_name='Data de Início das Atividades')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Social')),
                ('opcao_pelo_simples', models.BooleanField(default=False, verbose_name='Optante pelo Simples')),
                ('data_opcao_pelo_simples', models.DateField(blank=True, null=True, verbose_name='Data da Opção pelo Simples')),
                ('data_exclusao_do_simples', models.DateField(blank=True, null=True, verbose_name='Data da Exclusão do Simples')),
                ('opcao_pelo_mei', models.BooleanField(default=False, verbose_name='Optante pelo MEI')),
                ('ddd_telefone_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('ddd_telefone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('ddd_fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('email_receita', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Cadastrado na Receita')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'db_table': 'fabricantes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Produto',
                'verbose_name_plural': 'Grupos de Produto',
                'db_table': 'grupos_produto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'db_table': 'lojas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
            options={
                'db_table': 'parametros',
            },
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('codigo_master', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Master')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('principal', models.BooleanField(default=False, verbose_name='Contato Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('chatwoot_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID no ChatWoot')),
                ('chatwoot_inbox_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID da Caixa de Entrada no ChatWoot')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'db_table': 'cliente_contatos',
                'ordering': ['-principal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('projetista', 'Projetista'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.fabricante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.grupoproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='core.loja')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ClienteCnaeSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cnae', models.CharField(help_text='Código CNAE da Receita Federal (ex: 4761003)', max_length=10, verbose_name='Código CNAE')),
                ('descricao_cnae', models.CharField(help_text='Descrição oficial da atividade econômica', max_length=200, verbose_name='Descrição do CNAE')),
                ('ordem', models.PositiveSmallIntegerField(default=1, help_text='Ordem do CNAE secundário (1, 2, 3...)', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnaes_secundarios', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'CNAE Secundário do Cliente',
                'verbose_name_plural': 'CNAEs Secundários dos Clientes',
                'db_table': 'cliente_cnaes_secundarios',
                'ordering': ['cliente', 'ordem'],
                'indexes': [models.Index(fields=['cliente', 'ordem'], name='idx_cliente_cnae_ordem'), models.Index(fields=['codigo_cnae'], name='idx_cnae_codigo')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'codigo_cnae'), name='unique_cliente_cnae')],
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('numero_nf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número NF')),
                ('serie_nf', models.CharField(blank=True, max_length=3, null=True, verbose_name='Série NF')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('anomes', models.CharField(db_index=True, help_text='Formato: YYYYMM', max_length=6, verbose_name='Ano/Mês')),
                ('ano', models.CharField(db_index=True, max_length=4, verbose_name='Ano')),
                ('mes', models.CharField(db_index=True, max_length=2, verbose_name='Mês')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('origem_sistema', models.CharField(default='BI', max_length=20, verbose_name='Sistema de Origem')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.cliente', verbose_name='Cliente')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.fabricante', verbose_name='Fabricante')),
                ('grupo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.grupoproduto', verbose_name='Grupo de Produto')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loja', verbose_name='Loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto', verbose_name='Produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'vendas',
                'ordering': ['-data_venda'],
                'indexes': [models.Index(fields=['loja', 'vendedor', 'produto'], name='vendas_loja_id_e3f370_idx'), models.Index(fields=['cliente'], name='vendas_cliente_bc902f_idx'), models.Index(fields=['data_venda'], name='vendas_data_ve_d643c7_idx'), models.Index(fields=['anomes'], name='vendas_anomes_a0457b_idx'), models.Index(fields=['ano', 'mes'], name='vendas_ano_a0457b_idx')],
            },
        ),
    ]
