# Generated by Django 5.1.7 on 2025-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='vendedor_nf',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Vendedor NF'),
        ),
    ]
