# Generated by Django 5.1.7 on 2025-05-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteitem',
            options={'ordering': ['codigo'], 'verbose_name': 'Item do Cliente', 'verbose_name_plural': 'Itens dos Clientes'},
        ),
        migrations.AddField(
            model_name='clienteitem',
            name='codigo',
            field=models.CharField(default=0, max_length=20, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteitem',
            name='codigo_master',
            field=models.CharField(default=0, max_length=20, verbose_name='Código Master'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_master', models.CharField(max_length=20, verbose_name='Código Master')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('principal', models.BooleanField(default=False, verbose_name='Contato Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'db_table': 'cliente_contatos',
                'ordering': ['-principal', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
