# Generated by Django 5.1.7 on 2025-06-04 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendas_vendedor_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_vendedor',
            field=models.CharField(blank=True, help_text='Nome do vendedor (preenchido automaticamente)', max_length=100, null=True, verbose_name='Nome do Vendedor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacao_cadastral',
            field=models.CharField(blank=True, choices=[('01', 'Nula'), ('02', 'Ativa'), ('03', 'Suspensa'), ('04', 'Inapta'), ('08', 'Baixada'), ('2.0', 'Ativa'), ('3.0', 'Suspensa'), ('4.0', 'Inapta'), ('8.0', 'Baixada')], max_length=20, null=True, verbose_name='Situação Cadastral'),
        ),
        migrations.CreateModel(
            name='LogSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bi', 'BI SysFat'), ('receita', 'Receita Federal'), ('chatwoot', 'ChatWoot')], max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('registros_processados', models.IntegerField(default=0)),
                ('registros_criados', models.IntegerField(default=0)),
                ('registros_atualizados', models.IntegerField(default=0)),
                ('registros_com_erro', models.IntegerField(default=0)),
                ('status', models.CharField(default='iniciado', max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'db_table': 'log_sincronizacao',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
