# Generated by Django 5.1.7 on 2025-05-03 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clienteitem_options_clienteitem_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseProduto',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classe de Produto',
                'verbose_name_plural': 'Classes de Produto',
                'db_table': 'classes_produto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'db_table': 'lojas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep_fiscal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnae_descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do CNAE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE Principal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_loja',
            field=models.CharField(blank=True, help_text='Código de 3 dígitos da loja (NUMLOJ no SysFat)', max_length=3, null=True, verbose_name='Código da Loja'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_master',
            field=models.CharField(blank=True, help_text='Se preenchido, indica que este é um sub-cliente', max_length=20, null=True, verbose_name='Código Master'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_municipio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do Município'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_natureza_juridica',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Natureza Jurídica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_vendedor',
            field=models.CharField(blank=True, help_text='Código de 3 dígitos do vendedor (CODVEN no SysFat)', max_length=3, null=True, verbose_name='Código do Vendedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_exclusao_do_simples',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Exclusão do Simples'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_inicio_atividade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início das Atividades'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_opcao_pelo_simples',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Opção pelo Simples'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_situacao_cadastral',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Situação Cadastral'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ultima_verificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Verificação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ddd_fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ddd_telefone_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ddd_telefone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_receita',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Cadastrado na Receita'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_fiscal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_fiscal',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_situacao_cadastral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo da Situação Cadastral'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza Jurídica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome/Razão Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_vendedor',
            field=models.CharField(blank=True, help_text='Nome do vendedor (VEND no SysFat)', max_length=100, null=True, verbose_name='Nome do Vendedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='opcao_pelo_mei',
            field=models.BooleanField(default=False, verbose_name='Optante pelo MEI'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='opcao_pelo_simples',
            field=models.BooleanField(default=False, verbose_name='Optante pelo Simples'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='porte_empresa',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Porte da Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='situacao_cadastral',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação Cadastral'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], default='cpf', max_length=10, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, help_text='Unidade Federativa (UF no SysFat)', max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='clientecontato',
            name='chatwoot_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID no ChatWoot'),
        ),
        migrations.AddField(
            model_name='clientecontato',
            name='chatwoot_inbox_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID da Caixa de Entrada no ChatWoot'),
        ),
        migrations.AddField(
            model_name='clientecontato',
            name='codigo',
            field=models.CharField(default=0, max_length=20, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientecontato',
            name='ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_loja',
            field=models.CharField(blank=True, help_text='Código de 3 dígitos da loja (NUMLOJ no SysFat)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_vendedor',
            field=models.CharField(blank=True, help_text='Código de 3 dígitos do vendedor (CODVEN no SysFat)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='clientecontato',
            name='codigo_master',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Master'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('projetista', 'Projetista'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestor', 'Gestor'), ('vendedor', 'Vendedor')], max_length=20),
        ),
        migrations.CreateModel(
            name='LogSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bi', 'BI SysFat'), ('receita', 'Receita Federal'), ('chatwoot', 'ChatWoot')], max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('registros_processados', models.IntegerField(default=0)),
                ('registros_criados', models.IntegerField(default=0)),
                ('registros_atualizados', models.IntegerField(default=0)),
                ('registros_com_erro', models.IntegerField(default=0)),
                ('status', models.CharField(default='iniciado', max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'db_table': 'log_sincronizacao',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.classeproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='core.loja')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('anomes', models.CharField(db_index=True, help_text='Formato: AAMM (Ano e Mês)', max_length=4, verbose_name='Ano/Mês')),
                ('ano', models.CharField(db_index=True, max_length=2, verbose_name='Ano')),
                ('mes', models.CharField(db_index=True, max_length=2, verbose_name='Mês')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('numero_nf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número NF')),
                ('serie_nf', models.CharField(blank=True, max_length=3, null=True, verbose_name='Série NF')),
                ('origem_sistema', models.CharField(default='Clipper', max_length=20, verbose_name='Sistema de Origem')),
                ('data_sincronizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Sincronização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('classe_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_bi', to='core.classeproduto', verbose_name='Classe de Produto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_bi', to='core.cliente', verbose_name='Cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loja', verbose_name='Loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto', verbose_name='Produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Registro de BI',
                'verbose_name_plural': 'Registros de BI',
                'db_table': 'registros_bi',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.DeleteModel(
            name='ClienteItem',
        ),
        migrations.AddIndex(
            model_name='registrobi',
            index=models.Index(fields=['loja', 'vendedor', 'produto'], name='registros_b_loja_id_e77e10_idx'),
        ),
        migrations.AddIndex(
            model_name='registrobi',
            index=models.Index(fields=['cliente'], name='registros_b_cliente_160f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrobi',
            index=models.Index(fields=['data_venda'], name='registros_b_data_ve_3fdf05_idx'),
        ),
        migrations.AddIndex(
            model_name='registrobi',
            index=models.Index(fields=['anomes'], name='registros_b_anomes_000bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='registrobi',
            index=models.Index(fields=['ano', 'mes'], name='registros_b_ano_000bf9_idx'),
        ),
    ]
