# Generated by Django 5.1.7 on 2025-06-05 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_nome_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
