# Generated by Django 5.1.7 on 2025-05-03 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classeproduto_loja_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cep_fiscal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade_fiscal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_municipio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco_fiscal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_fiscal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Última Compra'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_logradouro',
            field=models.CharField(blank=True, help_text='Ex: Rua, Avenida, Alameda, etc.', max_length=20, null=True, verbose_name='Tipo de Logradouro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro'),
        ),
    ]
