# Generated by Django 5.1.7 on 2025-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nome_vendedor',
        ),
        migrations.AlterField(
            model_name='clientecontato',
            name='ultima_sincronizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
    ]
