# Generated by Django 5.1.7 on 2025-06-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cliente_cep_fiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCnaeSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cnae', models.CharField(help_text='Código CNAE da Receita Federal (ex: 4761003)', max_length=10, verbose_name='Código CNAE')),
                ('descricao_cnae', models.CharField(help_text='Descrição oficial da atividade econômica', max_length=200, verbose_name='Descrição do CNAE')),
                ('ordem', models.PositiveSmallIntegerField(default=1, help_text='Ordem do CNAE secundário (1, 2, 3...)', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnaes_secundarios', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'CNAE Secundário do Cliente',
                'verbose_name_plural': 'CNAEs Secundários dos Clientes',
                'db_table': 'cliente_cnaes_secundarios',
                'ordering': ['cliente', 'ordem'],
                'indexes': [models.Index(fields=['cliente', 'ordem'], name='idx_cliente_cnae_ordem'), models.Index(fields=['codigo_cnae'], name='idx_cnae_codigo')],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'codigo_cnae'), name='unique_cliente_cnae')],
            },
        ),
    ]
