# Generated by Django 5.1.7 on 2025-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vendas_vendas_loja_id_5301d2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendas',
            name='vendas_loja_id_e3f370_idx',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='vendedor',
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['loja', 'produto'], name='vendas_loja_id_d23fea_idx'),
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['vendedor_nf'], name='vendas_vendedo_a35297_idx'),
        ),
    ]
