# Generated by Django 5.1.7 on 2025-06-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_vendas_vendas_loja_id_d23fea_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendas',
            name='vendas_cliente_bc902f_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendas',
            name='vendas_loja_id_e3f370_idx',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='vendedor',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='vendedor_nf',
            field=models.CharField(blank=True, help_text='Código do vendedor que fez a venda (histórico da NF)', max_length=3, null=True, verbose_name='Vendedor da NF'),
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['loja', 'cliente'], name='vendas_loja_id_5301d2_idx'),
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['vendedor_nf'], name='vendas_vendedo_a35297_idx'),
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['cliente', 'data_venda'], name='vendas_cliente_dd456a_idx'),
        ),
    ]
