# Generated by Django 5.1.7 on 2025-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vendas_vendas_cliente_bc902f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('rascunho', 'Rascunho'), ('outros', 'Outros')], default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
